// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihpqkjvcjnvrmhueullt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlocHFranZjam52cm1odWV1bGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NjAyNDAsImV4cCI6MjA1NDAzNjI0MH0.73mOTm9QpxnnBqQqU2dp9tBwz6reYj7VNHRISJV_qHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);